<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>API Gateway emulation for Kite, routing HTTP requests to emulated Lambda functions.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kite.Core\Kite.Core.csproj" />
    <ProjectReference Include="..\Kite.Lambda\Kite.Lambda.csproj" />
  </ItemGroup>
</Project>
