<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Amazon SNS emulation for Kite: topics and subscriptions.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kite.Core\Kite.Core.csproj" />
  </ItemGroup>
</Project>
