<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Amazon S3 emulation, including S3-to-Lambda triggers, for Kite, an AWS cloud emulator for .NET.</Description>
    <PackageTags>$(PackageTags);s3;storage</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Amazon.Lambda.S3Events" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kite.Core\Kite.Core.csproj" />
    <ProjectReference Include="..\Kite.Lambda\Kite.Lambda.csproj" />
  </ItemGroup>
</Project>
