<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Amazon S3 emulation for Kite, including S3 event notifications to Lambda.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Amazon.Lambda.S3Events" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kite.Core\Kite.Core.csproj" />
    <ProjectReference Include="..\Kite.Lambda\Kite.Lambda.csproj" />
  </ItemGroup>
</Project>
