<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>In-process AWS Lambda execution and endpoints for Kite, an AWS cloud emulator for .NET. Runs and debugs .NET Lambda functions directly in your IDE.</Description>
    <PackageTags>$(PackageTags);serverless</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Amazon.Lambda.Core" Version="2.5.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.3" />
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="2.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kite.Core\Kite.Core.csproj" />
  </ItemGroup>
</Project>
