<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Amazon SQS emulation, including SQS-to-Lambda triggers, for Kite, an AWS cloud emulator for .NET.</Description>
    <PackageTags>$(PackageTags);sqs;queue</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Amazon.Lambda.SQSEvents" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kite.Core\Kite.Core.csproj" />
    <ProjectReference Include="..\Kite.Lambda\Kite.Lambda.csproj" />
  </ItemGroup>
</Project>
