<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Amazon ECS emulation for Kite: clusters, task definitions and tasks.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kite.Core\Kite.Core.csproj" />
  </ItemGroup>
</Project>
